project:
  type: website
  output-dir: docs
website:
  title: "a_quarto_website1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: website
    css: styles.css
    toc: true




